/*
 * IRQPriorityConf.h
 *
 *  Created on: 31 бер. 2020 р.
 *      Author: MaxCm
 */

#ifndef _IRQPRIORITYCONFIG_H_
#define _IRQPRIORITYCONFIG_H_

#define OVERCURRENT12V_TIMER_PRIORITY	3
#define UARTEXTENSION_RX_PRIORITY		4
#define UARTEXTENSION_TX_PRIORITY		4

#define SPIEXTENSION_SPI_PRIORITY		3
#define WIRELESSINTERFACE_SPI_PRIORITY	2

#define VOLTAGEMETER_EOC_PRIORITY		3

#define USERINTERFACE_TIMER_PRIORITY	3



#endif /* IRQPRIORITYCONFIG_H_ */
